Vagrant.configure(2) do |vb|

    # vagrant box
    vb.vm.box = "ubuntu/trusty64"

    # ports to access the virtual machine
    vb.vm.network "forwarded_port", guest: 8000, host: 8111,
        auto_correct: true

    # shared folder setup
    vb.vm.synced_folder ".", "/home/vagrant/django_starter"

    # SSH agent forwarding
    vb.ssh.forward_agent = true

    # Set the amount of memory and cpus allocated to your VM
    vb.memory = 1024
    vb.cpus = 2

end